# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: Smile's Cornerstone weblog
title: Smile's Cornerstone weblog
email: thibault.milan@smile.eu
description: >- # this means to ignore newlines until "baseurl:"
  Smile's weblog about tech. Cuting edge tech popularization, hightly technical walkthrougt 
  in an open sharing with the world mindset.
logo: 'assets/images/logo.png'
favicon: assets/images/logo.png'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: ''
disqus: ''
mailchimp-list: 'https://medium.us18.list-manage.com/subscribe/post?u=4d3484a4e4a58a42c2bc028f5&amp;id=7db7ed73c3'

include: ["_pages"]


# Conversion
excerpt_separator: '<br class="exceprt_separator">'

# Outputting
permalink: /:title/
timezone: Europe/Luxembourg

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-youtube
  - jekyll-maps
  - jekyll-gist
  - jekyll-twitter-plugin
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination 
paginate: 6
paginate_path: /page:num/

feed:
    posts_limits: 20
    excerpt_only: false

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, _posts/assets]

maps:
    google:
        api_key: ''
# Have a per category feed
#    categories:
#        - techwatch
# Generate a feed for all tags
#    tags: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
