---
name: Smile's Cornerstone weblog
title: Smile's Cornerstone weblog
email: thibault.milan@smile.eu
description: Smile's weblog about tech. Cuting edge tech popularization, hightly technical
  walkthrougt  in an open sharing with the world mindset.
logo: assets/images/logo.png
favicon: assets/images/logo.png'
baseurl: ''
url: ''
google_analytics: ''
disqus: ''
mailchimp-list: https://medium.us18.list-manage.com/subscribe/post?u=4d3484a4e4a58a42c2bc028f5&amp;id=7db7ed73c3
include:
- _pages
excerpt_separator: <br class="exceprt_separator">
permalink: "/:title/"
timezone: Europe/Luxembourg
theme: minima
plugins:
- jekyll-feed
- jekyll-archives
- jekyll-youtube
- jekyll-maps
- jekyll-gist
- jekyll-twitter-plugin
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
jekyll-archives:
  enabled:
  - categories
  layout: archive
  permalinks:
    category: "/category/:name/"
paginate: 6
paginate_path: "/page:num/"
feed:
  posts_limits: 20
  excerpt_only: false
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
adsense: disabled
adsense-data-ad-client: ''
adsense-data-ad-slot: ''
lazyimages: disabled
exclude:
- changelog.md
- LICENSE.txt
- README.md
- Gemfile
- Gemfile.lock
- _posts/assets
maps:
  google:
    api_key: ''
favison: ''
