---
name: Smile's Cornerstone weblog
title: Smile's Cornerstone weblog
email: thibault.milan@smile.eu
description: Smile's weblog about tech. Cuting edge tech popularization, hightly technical
  walkthrougt  in an open sharing with the world mindset.
logo: "/uploads/thumbnail_logo_smile_orange-baseline.jpg"
favicon: assets/images/logo.png'
baseurl: ''
url: ''
google_analytics: ''
disqus: ''
mailchimp-list: https://medium.us18.list-manage.com/subscribe/post?u=4d3484a4e4a58a42c2bc028f5&amp;id=7db7ed73c3
include:
- _pages
excerpt_separator: <br class="exceprt_separator">
permalink: "/:title/"
timezone: Europe/Luxembourg

# Conversion
excerpt_separator: '<br class="exceprt_separator">'

# Outputting
permalink: /:title/
timezone: Europe/Luxembourg

# Build settings
plugins:
- jekyll-feed
- jekyll-archives
- jekyll-youtube
- jekyll-maps
- jekyll-gist
- jekyll-twitter-plugin
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
jekyll-archives:
  enabled:
  - categories
  layout: archive
  permalinks:
    category: "/category/:name/"
paginate: 6
paginate_path: "/page:num/"

feed:
  posts_limits: 20
  excerpt_only: false

jekyll-archives:
    enabled:
        - year
        - month
        - categories
        - tags
    layout: archive

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
adsense: disabled
adsense-data-ad-client: ''
adsense-data-ad-slot: ''
lazyimages: disabled
exclude:
- changelog.md
- LICENSE.txt
- README.md
- Gemfile
- Gemfile.lock
- _posts/assets

maps:
  google:
    api_key: ''
favison: "/uploads/medium_favicon_logo_smile.jpg"


# Have a per category feed
#    categories:
#        - techwatch
# Generate a feed for all tags
#    tags: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
