---
name: Smile's Tech weblog
title: Smile's Tech weblog
email: thibault.milan@smile.eu
description: Smile's weblog about tech. Cuting edge tech popularization, hightly technical
  walkthrougt  in an open sharing with the world mindset.
logo: "uploads/thumbnail_logo_smile_orange-baseline.jpg"
favicon: assets/images/logo.png'
baseurl: ''
url: 'https://tech.smile.eu'
google_analytics: ''
disqus: ''

include:
- _pages
excerpt_separator: <br class="exceprt_separator">
permalink: "/:title/"
timezone: Europe/Luxembourg

collections:
  authors:
    output: true

defaults:
  -
    scope:
      path: "assets/iframes/*"
    values:
      sitemap: false
  -
    scope:
      path: "assets/js/*"
    values:
      sitemap: false
  -
    scope:
      path: "assets/fonts/*"
    values:
      sitemap: false
  -
    scope:
      path: "assets/css/*"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-youtube
  - jekyll-maps
  - jekyll-gist
  - jekyll-twitter-plugin
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
    - month
  layout: archive
  permalinks:
    category: '/category/:name/'
    tag: 'tag/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

feed:
    posts_limits: 20
    excerpt_only: false

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude:
- changelog.md
- LICENSE.txt
- README.md
- Gemfile
- Gemfile.lock
- _posts/assets

maps:
    google:
        api_key: ''

# Have a per category feed
#    categories:
#        - techwatch
# Generate a feed for all tags
#    tags: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
